#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfc44;
constexpr uint24_t FX_DATA_BYTES = 240614;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t dpad = 0x000000;
constexpr uint24_t abutton = 0x000182;
constexpr uint24_t bbutton = 0x0001E4;
constexpr uint24_t catg = 0x000246;
constexpr uint24_t idlelsmall = 0x000848;
constexpr uint24_t idleusmall = 0x00204A;
constexpr uint24_t idlefsmall = 0x00384C;
constexpr uint24_t walkfsmall = 0x00504E;
constexpr uint24_t idlersmall = 0x006E50;
constexpr uint24_t walkleftsmall = 0x008652;
constexpr uint24_t walkrightsmall = 0x00A454;
constexpr uint24_t idlel = 0x00C256;
constexpr uint24_t idleu = 0x012258;
constexpr uint24_t walkf = 0x01825A;
constexpr uint24_t walkleft = 0x01FA5C;
constexpr uint24_t walkright = 0x02725E;
constexpr uint24_t idler = 0x02EA60;
constexpr uint24_t idlef = 0x034A62;
constexpr uint24_t test = 0x03AA64;
